//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PFC.Hubs
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatPrivMensMaster
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public string EmailID { get; set; }
    }
}
