//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PFC.Hubs
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SignalREntities : DbContext
    {
        public SignalREntities()
            : base("name=SignalREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ChatMessageDetail> ChatMessageDetail { get; set; }
        public DbSet<ChatPrivateMessageDetails> ChatPrivateMessageDetails { get; set; }
        public DbSet<ChatPrivateMessageMaster> ChatPrivateMessageMaster { get; set; }
        public DbSet<ChatUserDetail> ChatUserDetail { get; set; }
    }
}
